# Generated by Django 4.2.4 on 2023-10-23 00:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250, verbose_name='Nombre')),
                ('descripcion', models.CharField(max_length=250, verbose_name='descripcion del producto')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_de_cliente', models.IntegerField(verbose_name='numero de cliente')),
                ('nombre', models.CharField(max_length=250, verbose_name='nombre')),
                ('apellido', models.CharField(max_length=250, verbose_name='apellido')),
                ('dni', models.IntegerField(verbose_name='DNI')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.IntegerField(verbose_name='codigo del producto')),
                ('nombre', models.CharField(max_length=250, verbose_name='nombre del producto')),
                ('descripcion', models.CharField(max_length=250, verbose_name='descripcion del producto')),
                ('precio', models.FloatField(verbose_name='precio del producto')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='ItemInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(verbose_name='cantidad de unidades del producto en inventario')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.producto')),
            ],
        ),
        migrations.CreateModel(
            name='ItemCarrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(verbose_name='cantidad de unidades del producto en carrito')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateField(verbose_name='fecha de creacion del inventario')),
                ('fecha_modificacion', models.DateField(verbose_name='fecha de la ultima modificacion')),
                ('items_inventario', models.ManyToManyField(to='ecommerce.iteminventario')),
            ],
        ),
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_de_compra', models.DateField(verbose_name='fecha de compra')),
                ('monto_total', models.FloatField(verbose_name='monto total de la compra')),
                ('direccion_entrega', models.CharField(max_length=250, verbose_name='direccion de entrega')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.cliente')),
                ('items_carrito', models.ManyToManyField(to='ecommerce.itemcarrito')),
            ],
        ),
    ]
