# Generated by Django 4.2.4 on 2023-11-17 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250, verbose_name='Nombre')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_de_cliente', models.IntegerField(verbose_name='Numero de cliente')),
                ('nombre', models.CharField(max_length=250, verbose_name='Nombre')),
                ('apellido', models.CharField(max_length=250, verbose_name='Apellido')),
                ('dni', models.IntegerField(verbose_name='DNI')),
                ('email', models.EmailField(max_length=250, verbose_name='E-Mail')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250, verbose_name='Nombre')),
                ('descripcion', models.CharField(max_length=250, verbose_name='Descripcion')),
                ('precio', models.FloatField(verbose_name='Precio')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad')),
                ('imagen', models.ImageField(null=True, upload_to='imagenes/', verbose_name='Imagen del producto')),
                ('promocion', models.BooleanField(null=True, verbose_name='Promocion')),
                ('categoria', models.ManyToManyField(to='administracion.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='ItemCarrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(verbose_name='cantidad')),
                ('subtotal', models.FloatField(verbose_name='Subtotal')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_de_compra', models.DateField(verbose_name='Fecha de compra')),
                ('monto_total', models.FloatField(verbose_name='Monto total')),
                ('direccion_entrega', models.CharField(max_length=250, verbose_name='Direccion de entrega')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.cliente')),
                ('items_carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.itemcarrito')),
            ],
        ),
    ]
