# Generated by Django 4.2.4 on 2023-11-15 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='promocion',
            field=models.BooleanField(null=True, verbose_name='Promocion'),
        ),
    ]
